data:extend({
	{
		type = "item-group",
		name = "raw-metallurgy",
		icon = "__base__/graphics/technology/advanced-material-processing.png",
		icon_size = 256,
		icon_mipmaps = 4,
		inventory_order = "f",
		order = "e",
	},
	{
		type = "item-subgroup",
		name = "raw-metallurgy",
		group = "raw-metallurgy",
		order = "a",
	},
	{
		type = "item-subgroup",
		name = "raw-magnetite",
		group = "raw-metallurgy",
		order = "b",
	},
	{
		type = "item-subgroup",
		name = "raw-malachite",
		group = "raw-metallurgy",
		order = "c",
	},
	{
		type = "item-group",
		name = "refined-metallurgy",
		icon = "__base__/graphics/technology/advanced-material-processing-2.png",
		icon_size = 256,
		icon_mipmaps = 4,
		inventory_order = "g",
		order = "f",
	},
	{
		type = "item-subgroup",
		name = "refined-metallurgy",
		group = "refined-metallurgy",
		order = "a",
	},
	{
		type = "item-group",
		name = "metallurgy-processes",
		icon = "__base__/graphics/technology/coal-liquefaction.png",
		icon_size = 256,
		icon_mipmaps = 4,
		inventory_order = "h",
		order = "g",
	},
	{
		type = "item-subgroup",
		name = "metallurgy-processes",
		group = "metallurgy-processes",
		order = "a",
	},
	{
		type = "item-group",
		name = "sam-recipes",
		icon = "__base__/graphics/technology/steel-processing.png",
		icon_size = 256,
		icon_mipmaps = 4,
		inventory_order = "i",
		order = "h",
	},
	{
		type = "item-subgroup",
		name = "sam-recipes",
		group = "sam-recipes",
		order = "a",
	},
	{
		type = "item-group",
		name = "sam-fluid-recipes",
		icon = "__base__/graphics/technology/sulfur-processing.png",
		icon_size = 256,
		icon_mipmaps = 4,
		inventory_order = "j",
		order = "i",
	},
	{
		type = "item-subgroup",
		name = "sam-fluid-recipes",
		group = "sam-fluid-recipes",
		order = "a",
	},
})
