data:extend({
	{
		type = "fluid",
		name = "molten-iron",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "aquatic-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.8, b = 0.8 },
		flow_color = { r = 0.2, g = 0.8, b = 0.8 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "hydrochlorine",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.1, g = 0.8, b = 0.5 },
		flow_color = { r = 0.1, g = 0.8, b = 0.5 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "aquamethane",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.8, b = 0.2 },
		flow_color = { r = 0.2, g = 0.8, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "methanol",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.6, b = 0.2 },
		flow_color = { r = 0.2, g = 0.6, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "magnetite-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "malachite-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "nickel-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "cobalt-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "aluminum-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "titanium-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "lead-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "tin-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "chromium-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "thorium-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "uranium-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "samarium-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "neodymium-slurry",
		subgroup = "sam-fluid-recipes",
		default_temperature = 10,
		max_temperature = 10,
		base_color = { r = 0.2, g = 0.2, b = 0.6 },
		flow_color = { r = 0.2, g = 0.2, b = 0.4 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "molten-copper",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "molten-nickel",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "molten-aluminum",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "molten-cobalt",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "molten-titanium",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "molten-chromium",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "coolant",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "chemical-gas",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "chemical-water",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "liquid-air",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "mineral-oil",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "noble-gases",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "nitrogen",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "hydrogen",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "oxygen",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "fluorine",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "chlorine",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "carbon-dioxide",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "ammonia",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "ammonia-hydroxide",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "sodium-chloride",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "muriatic-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "nitric-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "carbonic-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "chloric-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "azane-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "verelic-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "caudic-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "luret-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "buren-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "genhal-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "vixal-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "phaudec-acid",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "dilute-acid-solution",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "acid-cleaning-solution",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "motor-oil",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
	{
		type = "fluid",
		name = "chemical-oil",
		subgroup = "sam-fluid-recipes",
		default_temperature = 150,
		max_temperature = 300,
		heat_capacity = "0.2KJ",
		base_color = { r = 8, g = 0.2, b = 0.6 },
		flow_color = { r = 0.7, g = 0.55, b = 0.2 },
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		order = "a[fluid]-a[water]",
		auto_barrel = true,
	},
})
