data:extend({
	--Magnetite Ore
	{
		type = "recipe",
		name = "iron-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "magnetite-ore", 4 } },
		results = { { "iron-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-magnetite", 1 } },
		results = { { "iron-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "magnetite-powder", 2 } },
		results = { { "iron-plate", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-magnetite-powder", 1 } },
		results = { { "iron-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-magnetite-powder", 1 } },
		results = { { "iron-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "magnetite-rock", 2 } },
		results = { { "iron-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "magnetite-chunk", 1 } },
		results = { { "iron-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "magnetite-shard", 1 } },
		results = { { "iron-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-magnetite-shard", 1 } },
		results = { { "iron-plate", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-magnetite-ore", 10 } },
		results = { { "iron-plate", 20 } },
		energy_required = 20,
		enabled = true,
	},
	--regular iron smelting
	{
		type = "recipe",
		name = "iron-plate",
		category = "smelting",
		ingredients = { { "iron-ore", 2 } },
		results = { { "iron-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Haematite Smelting
	{
		type = "recipe",
		name = "iron-plate-raw2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "haematite-ore", 4 } },
		results = { { "iron-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	--Copper Smelting
	{
		type = "recipe",
		name = "copper-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "malachite-ore", 4 } },
		results = { { "copper-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-malachite", 1 } },
		results = { { "copper-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "malachite-powder", 2 } },
		results = { { "copper-plate", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-malachite-powder", 1 } },
		results = { { "copper-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-malachite-powder", 1 } },
		results = { { "copper-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "malachite-rock", 2 } },
		results = { { "copper-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "malachite-chunk", 1 } },
		results = { { "copper-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "malachite-shard", 1 } },
		results = { { "copper-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-malachite-shard", 1 } },
		results = { { "copper-plate", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-malachite-ore", 2 } },
		results = { { "copper-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Copper Ore Smelting
	{
		type = "recipe",
		name = "copper-plate",
		category = "smelting",
		ingredients = { { "copper-ore", 2 } },
		results = { { "copper-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Nickel Smelting
	{
		type = "recipe",
		name = "nickel-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "laterite-ore", 2 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Raw Nickel Smelting
	{
		type = "recipe",
		name = "nickel-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-ore", 4 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-nickel", 1 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-powder", 2 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-nickel-powder", 1 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-nickel-powder", 1 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-rock", 2 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-chunk", 1 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-shard", 1 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-nickel-shard", 1 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-nickel-ore", 2 } },
		results = { { "nickel-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Cobalt Smelting
	{
		type = "recipe",
		name = "cobalt-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "cobaltite-ore", 6 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Raw Cobalt Smelting
	{
		type = "recipe",
		name = "cobalt-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "cobalt-ore", 4 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-cobalt", 1 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "cobalt-powder", 2 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-cobalt-powder", 1 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-cobalt-powder", 1 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "cobalt-rock", 2 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "cobalt-chunk", 1 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "cobalt-shard", 1 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-cobalt-shard", 1 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "imperfect-cobalt", 2 } },
		results = { { "cobalt-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-cobalt-ore", 1 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-10",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-cobalt-ore", 1 } },
		results = { { "cobalt-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Raw Aluminum Smelting
	{
		type = "recipe",
		name = "aluminum-plate-bauxite",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "bauxite-ore", 2 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Raw Aluminum Smelting
	{
		type = "recipe",
		name = "aluminum-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "aluminum-ore", 4 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-aluminum", 1 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "aluminum-powder", 2 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-aluminum-powder", 1 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-aluminum-powder", 1 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "aluminum-rock", 2 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "aluminum-chunk", 1 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "aluminum-shard", 1 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-aluminum-shard", 1 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-aluminum-ore", 2 } },
		results = { { "aluminum-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Titanium Smelting
	{
		type = "recipe",
		name = "titanium-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "titanium-ore", 4 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-titanium", 1 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "titanium-powder", 2 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-titanium-powder", 1 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-titanium-powder", 1 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "titanium-rock", 2 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "titanium-chunk", 1 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "titanium-shard", 1 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-titanium-shard", 1 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-titanium-ore", 2 } },
		results = { { "titanium-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Chromium Smelting
	{
		type = "recipe",
		name = "chromium-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "chromite-ore", 4 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-chromium", 1 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "chromium-powder", 2 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-chromium-powder", 1 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-chromium-powder", 1 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "chromium-rock", 2 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "chromium-chunk", 1 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "chromium-shard", 1 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-chromium-shard", 1 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-chromium-ore", 2 } },
		results = { { "chromium-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Lead Smelting
	{
		type = "recipe",
		name = "lead-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "lead-ore", 4 } },
		results = { { "lead-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-lead", 1 } },
		results = { { "lead-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "lead-powder", 2 } },
		results = { { "lead-plate", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-lead-powder", 1 } },
		results = { { "lead-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-lead-powder", 1 } },
		results = { { "lead-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "lead-rock", 2 } },
		results = { { "lead-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "lead-chunk", 1 } },
		results = { { "lead-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "lead-shard", 1 } },
		results = { { "lead-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-lead-shard", 1 } },
		results = { { "lead-plate", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-lead-ore", 2 } },
		results = { { "lead-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Tin Smelting
	{
		type = "recipe",
		name = "tin-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "tin-ore", 4 } },
		results = { { "tin-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-tin", 1 } },
		results = { { "tin-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "tin-powder", 2 } },
		results = { { "tin-plate", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-tin-powder", 1 } },
		results = { { "tin-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-tin-powder", 1 } },
		results = { { "tin-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "tin-rock", 2 } },
		results = { { "tin-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "tin-chunk", 1 } },
		results = { { "tin-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "tin-shard", 1 } },
		results = { { "tin-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-tin-shard", 1 } },
		results = { { "tin-plate", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-tin-ore", 2 } },
		results = { { "tin-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Thorium Ore
	{
		type = "recipe",
		name = "thorium-ore-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-thorium", 1 } },
		results = { { "thorium-ore", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "thorium-ore-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "thorium-powder", 2 } },
		results = { { "thorium-ore", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "thorium-ore-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-thorium-powder", 1 } },
		results = { { "thorium-ore", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "thorium-ore-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-thorium-powder", 1 } },
		results = { { "thorium-ore", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "thorium-ore-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "thorium-rock", 2 } },
		results = { { "thorium-ore", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "thorium-ore-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "thorium-chunk", 1 } },
		results = { { "thorium-ore", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "thorium-ore-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "thorium-shard", 1 } },
		results = { { "thorium-ore", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "thorium-ore-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-thorium-shard", 1 } },
		results = { { "thorium-ore", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "thorium-ore-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-thorium-ore", 2 } },
		results = { { "thorium-ore", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Samarium Ore
	{
		type = "recipe",
		name = "samarium-ore-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-samarium", 1 } },
		results = { { "samarium-ore", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "samarium-ore-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "samarium-powder", 2 } },
		results = { { "samarium-ore", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "samarium-ore-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-samarium-powder", 1 } },
		results = { { "samarium-ore", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "samarium-ore-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-samarium-powder", 1 } },
		results = { { "samarium-ore", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "samarium-ore-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "samarium-rock", 2 } },
		results = { { "samarium-ore", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "samarium-ore-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "samarium-chunk", 1 } },
		results = { { "samarium-ore", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "samarium-ore-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "samarium-shard", 1 } },
		results = { { "samarium-ore", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "samarium-ore-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-samarium-shard", 1 } },
		results = { { "samarium-ore", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "samarium-ore-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-samarium-ore", 2 } },
		results = { { "samarium-ore", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Neodymium Ore
	{
		type = "recipe",
		name = "neodymium-ore-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "crushed-neodymium", 1 } },
		results = { { "neodymium-ore", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "neodymium-ore-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "neodymium-powder", 2 } },
		results = { { "neodymium-ore", 1 } },
		energy_required = 6,
		enabled = true,
	},
	{
		type = "recipe",
		name = "neodymium-ore-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-neodymium-powder", 1 } },
		results = { { "neodymium-ore", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "neodymium-ore-4",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-neodymium-powder", 1 } },
		results = { { "neodymium-ore", 1 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "neodymium-ore-5",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "neodymium-rock", 2 } },
		results = { { "neodymium-ore", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "neodymium-ore-6",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "neodymium-chunk", 1 } },
		results = { { "neodymium-ore", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "neodymium-ore-7",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "neodymium-shard", 1 } },
		results = { { "neodymium-ore", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "neodymium-ore-8",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "purified-neodymium-shard", 1 } },
		results = { { "neodymium-ore", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "neodymium-ore-9",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-neodymium-ore", 2 } },
		results = { { "neodymium-ore", 2 } },
		energy_required = 4,
		enabled = true,
	},
	--Alloys Smelting
	{
		type = "recipe",
		name = "chromium-steel",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "chromium-plate", 1 }, { "iron-plate", 9 } },
		results = { { "chromium-steel", 2 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "invar-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-plate", 1 }, { "iron-plate", 2 } },
		results = { { "invar-plate", 1 } },
		energy_required = 7.5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "incoloy-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-plate", 2 }, { "iron-plate", 1 }, { "chromium-plate", 1 } },
		results = { { "incoloy-plate", 1 } },
		energy_required = 7.5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "monel-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-plate", 2 }, { "copper-plate", 1 } },
		results = { { "monel-plate", 1 } },
		energy_required = 7.5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "kovar-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "iron-plate", 5 }, { "nickel-plate", 3 }, { "cobalt-plate", 2 } },
		results = { { "kovar-plate", 5 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nitinol-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-plate", 3 }, { "titanium-plate", 3 } },
		results = { { "kovar-plate", 5 } },
		energy_required = 10,
		enabled = true,
	},
	{
		type = "recipe",
		name = "soldering-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "lead-plate", 3 }, { "tin-plate", 3 } },
		results = { { "soldering-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "light-bronze-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "copper-plate", 1 }, { "tin-plate", 2 } },
		results = { { "light-bronze-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "duralumin-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "aluminum-plate", 3 }, { "copper-plate", 1 } },
		results = { { "duralumin-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "bronze-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "copper-plate", 16 }, { "aluminum-plate", 2 }, { "iron-plate", 1 }, { "nickel-plate", 1 } },
		results = { { "bronze-plate", 10 } },
		energy_required = 10,
		enabled = true,
	},
	{
		type = "recipe",
		name = "havar-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "cobalt-plate", 5 }, { "chromium-plate", 3 }, { "nickel-plate", 2 } },
		results = { { "havar-plate", 2 } },
		energy_required = 5,
		enabled = true,
	},
	--bulletproof Titanium
	{
		type = "recipe",
		name = "titanium5-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "titanium-plate", 4 }, { "aluminum-plate", 1 }, { "cobalt-plate", 2 } },
		results = { { "titanium5-plate", 2 } },
		energy_required = 5,
		enabled = true,
	},
	--Magnet Age
	{
		type = "recipe",
		name = "neodymium-magnet",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "neodymium-ore", 3 }, { "iron-plate", 3 } },
		results = { { "neodymium-magnet", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "permalloy-magnet",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-plate", 2 }, { "iron-plate", 2 } },
		results = { { "permalloy-magnet", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "smco-magnet",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "samarium-ore", 6 }, { "cobalt-plate", 3 } },
		results = { { "smco-magnet", 2 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "alnico-magnet",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = {
			{ "iron-plate", 31 },
			{ "cobalt-plate", 36 },
			{ "nickel-plate", 14 },
			{ "aluminum-plate", 8 },
			{ "titanium-plate", 8 },
			{ "copper-plate", 3 },
		},
		results = { { "alnico-magnet", 10 } },
		energy_required = 40,
		enabled = true,
	},
})
