data:extend({
	--Magnetite Ore
	{
		type = "recipe",
		name = "iron-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "magnetite-ore", 4 } },
		results = { { "iron-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "imperfect-magnetite", 1 } },
		results = { { "iron-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-magnetite-ore", 1 } },
		results = { { "iron-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "iron-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-magnetite-ore", 2 } },
		results = { { "iron-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--regular iron smelting
	{
		type = "recipe",
		name = "iron-plate",
		category = "smelting",
		ingredients = { { "iron-ore", 2 } },
		results = { { "iron-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Haematite Smelting
	{
		type = "recipe",
		name = "iron-plate-raw2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "haematite-ore", 1 } },
		results = { { "iron-plate", 1 } },
		energy_required = 2,
		enabled = true,
	},
	--Copper Smelting
	{
		type = "recipe",
		name = "copper-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "malachite-ore", 4 } },
		results = { { "copper-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "imperfect-malachite", 1 } },
		results = { { "copper-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-malachite-ore", 1 } },
		results = { { "copper-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "copper-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-malachite-ore", 2 } },
		results = { { "copper-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Copper Ore Smelting
	{
		type = "recipe",
		name = "copper-plate",
		category = "smelting",
		ingredients = { { "copper-ore", 2 } },
		results = { { "copper-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Nickel Smelting
	{
		type = "recipe",
		name = "nickel-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "laterite-ore", 2 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Raw Nickel Smelting
	{
		type = "recipe",
		name = "nickel-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-ore", 4 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "imperfect-nickel", 1 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-nickel-ore", 1 } },
		results = { { "nickel-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nickel-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-nickel-ore", 2 } },
		results = { { "nickel-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Cobalt Smelting
	{
		type = "recipe",
		name = "cobalt-plate-raw1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "cobaltite-ore", 6 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Raw Cobalt Smelting
	{
		type = "recipe",
		name = "cobalt-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "cobalt-ore", 4 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "imperfect-cobalt", 1 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-cobalt-ore", 1 } },
		results = { { "cobalt-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "cobalt-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-cobalt-ore", 2 } },
		results = { { "cobalt-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Raw Aluminum Smelting
	{
		type = "recipe",
		name = "aluminum-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "aluminum-ore", 4 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "imperfect-aluminum", 1 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-aluminum-ore", 1 } },
		results = { { "aluminum-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "aluminum-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-aluminum-ore", 2 } },
		results = { { "aluminum-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Titanium Smelting
	{
		type = "recipe",
		name = "titanium-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "titanium-ore", 4 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "imperfect-titanium", 1 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-titanium-ore", 1 } },
		results = { { "titanium-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "titanium-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-titanium-ore", 2 } },
		results = { { "titanium-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Chromium Smelting
	{
		type = "recipe",
		name = "chromium-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "chromite-ore", 4 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "imperfect-chromite", 1 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-chromite-ore", 1 } },
		results = { { "chromium-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "chromium-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-chromite-ore", 2 } },
		results = { { "chromium-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Lead Smelting
	{
		type = "recipe",
		name = "lead-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "lead-ore", 4 } },
		results = { { "lead-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "imperfect-lead", 1 } },
		results = { { "lead-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-lead-ore", 1 } },
		results = { { "lead-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "lead-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-lead-ore", 2 } },
		results = { { "lead-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Tin Smelting
	{
		type = "recipe",
		name = "tin-plate-raw",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "tin-ore", 4 } },
		results = { { "tin-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-1",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "imperfect-tin", 1 } },
		results = { { "tin-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-2",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "pure-tin-ore", 1 } },
		results = { { "tin-plate", 2 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "tin-plate-3",
		category = "smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "refined-tin-ore", 2 } },
		results = { { "tin-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	--Thorium Ores
	--Leaving this blank until I find a better way to refine thorium, samarium, and neodymium. May be removed entirely.
	--Samarium Ores
	--Neodymium Ores
	--Alloys Smelting
	{
		type = "recipe",
		name = "chromium-steel",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "chromium-plate", 2 },{ "coal", 2 }, { "iron-plate", 10 }, {"valuable-metal-ores", 5} },
		results = { { "chromium-steel", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "invar-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-plate", 1 }, { "iron-plate", 2 } },
		results = { { "invar-plate", 1 } },
		energy_required = 7.5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "incoloy-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-plate", 2 }, { "iron-plate", 1 }, { "chromium-plate", 1 }, {"valuable-metal-ores", 4} },
		results = { { "incoloy-plate", 1 } },
		energy_required = 7.5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "monel-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-plate", 2 }, { "copper-plate", 1 } },
		results = { { "monel-plate", 1 } },
		energy_required = 7.5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "kovar-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "iron-plate", 5 }, { "nickel-plate", 3 }, { "cobalt-plate", 2 } },
		results = { { "kovar-plate", 2 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "nitinol-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-plate", 3 }, { "titanium-plate", 3 }, {"valuable-metal-ores", 2} },
		results = { { "nitinol-plate", 1 } },
		energy_required = 10,
		enabled = true,
	},
	{
		type = "recipe",
		name = "soldering-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "lead-plate", 3 }, { "tin-plate", 3 } },
		results = { { "soldering-plate", 3 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "magnox-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "scarce-metal-ores", 2 }, { "aluminum-plate", 4 }, { "thorium-ore", 1 } },
		results = { { "magnox-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "thoralite-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "carbonatite-ore", 2 }, { "rare-earth-ore", 4 }, { "thorium-ore", 1 } },
		results = { { "thoralite-plate", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "light-bronze-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "copper-plate", 1 }, { "tin-plate", 2 } },
		results = { { "light-bronze-plate", 1 } },
		energy_required = 4,
		enabled = true,
	},
	{
		type = "recipe",
		name = "duralumin-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "aluminum-plate", 3 }, { "copper-plate", 1 } },
		results = { { "duralumin-plate", 1 } },
		energy_required = 5,
		enabled = true,
	},
	{
		type = "recipe",
		name = "bronze-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "copper-plate", 16 }, { "aluminum-plate", 2 }, { "iron-plate", 1 }, { "nickel-plate", 1 } },
		results = { { "bronze-plate", 10 } },
		energy_required = 10,
		enabled = true,
	},
	{
		type = "recipe",
		name = "havar-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "cobalt-plate", 5 }, { "chromium-plate", 3 }, { "nickel-plate", 2 } },
		results = { { "havar-plate", 2 } },
		energy_required = 5,
		enabled = true,
	},
	--bulletproof Titanium
	{
		type = "recipe",
		name = "titanium5-plate",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "titanium-plate", 4 }, { "aluminum-plate", 1 }, { "cobalt-plate", 2 }, {"valuable-metal-ores", 4} },
		results = { { "titanium5-plate", 2 } },
		energy_required = 5,
		enabled = true,
	},
	--Magnet Age
	{
		type = "recipe",
		name = "neodymium-magnet",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "neodymium-ore", 3 }, { "iron-plate", 3 } },
		results = { { "neodymium-magnet", 1 } },
		energy_required = 8,
		enabled = true,
	},
	{
		type = "recipe",
		name = "permalloy-magnet",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "nickel-plate", 2 }, { "iron-plate", 2 } },
		results = { { "permalloy-magnet", 1 } },
		energy_required = 3,
		enabled = true,
	},
	{
		type = "recipe",
		name = "smco-magnet",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = { { "samarium-ore", 6 }, { "cobalt-plate", 3 } },
		results = { { "smco-magnet", 2 } },
		energy_required = 2,
		enabled = true,
	},
	{
		type = "recipe",
		name = "alnico-magnet",
		category = "alloy-smelting",
		subgroup = "refined-metallurgy",
		ingredients = {
			{ "iron-plate", 29 },
			{ "cobalt-plate", 20 },
			{ "nickel-plate", 18 },
			{ "aluminum-plate", 7 },
			{ "titanium-plate", 6 },
			{ "copper-plate", 12 },
		},
		results = { { "alnico-magnet", 5 } },
		energy_required = 40,
		enabled = true,
	},
})
