data:extend({
	{
		type = "recipe",
		name = "laterite-crushing",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/laterite-ore.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 1,
		ingredients = { { "laterite-ore", 8 } },
		results = {
			{ "cobaltite-ore", 4 },
			{ "bauxite-ore", 4 },
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "bauxite-reduction",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/bauxite-ore.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 1,
		ingredients = { { "bauxite-ore", 8 } },
		results = {
			{ "titanium-ore", 4 },
			{ "aluminum-ore", 4 },
			{ "magnetite-ore", 2 },
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "crushed-cobaltite",
		category = "basic-crafting",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-crushed.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "cobaltite-ore", 4 },
		},
		result = "cobalt-rock",
		result_count = 3,
	},
	{
		type = "recipe",
		name = "crushed-bauxite",
		category = "basic-crafting",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/bauxite-ore.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "bauxite-ore", 4 },
		},
		result = "aluminum-rock",
		result_count = 3,
	},
	{
		type = "recipe",
		name = "chromite-reduction",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-ore.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 3,
		ingredients = { { "chromite-ore", 8 } },
		results = {
			{ "chromite-ore", 4 },
			{ "magnetite-ore", 4 },
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "aluminum-recycling",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/bauxite-ore.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 1,
		ingredients = { { "aluminum-ore", 8 } },
		results = {
			{ "bauxite-ore", 8 },
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "cobalt-recycling",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobaltite-ore.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 1,
		ingredients = { { "cobalt-ore", 8 } },
		results = {
			{ "cobaltite-ore", 8 },
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "direct-cobaltite",
		category = "crafting",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-ore.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "cobaltite-ore", 4 },
		},
		results = {
			{ "cobalt-ore", 4 },
			{ "stone", 2 },
		},
		main_product = "cobalt-ore",
	},
	{
		type = "recipe",
		name = "direct-bauxite",
		category = "crafting",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-ore.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "bauxite-ore", 4 },
		},
		results = {
			{ "aluminum-ore", 4 },
			{ "stone", 2 },
		},
		main_product = "aluminum-ore",
	},
	{
		type = "recipe",
		name = "cobaltite-reduction",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobaltite-ore.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 1,
		ingredients = { { "cobaltite-ore", 8 } },
		results = {
			{ "cobalt-ore", 4 },
			{ "magnetite-ore", 2 },
			{ "nickel-ore", 4 },
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "monazite-refining",
		icon = "__base__/graphics/icons/uranium-ore.png",
		category = "centrifuging",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 30,
		ingredients = { { "monazite-ore", 10 } },
		results = {
			{
				name = "uranium-ore",
				probability = 0.25,
				amount = 10,
			},
			{
				name = "thorium-ore",
				probability = 0.15,
				amount = 10,
			},
			{
				name = "rare-earth-ore",
				probability = 0.5,
				amount = 20,
			},
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "magnet-refining",
		icon = "__base__/graphics/icons/coal.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 8,
		ingredients = { { "rare-earth-ore", 10 } },
		results = {
			{
				name = "neodymium-ore",
				probability = 1,
				amount = 5,
			},
			{
				name = "samarium-ore",
				probability = 1,
				amount = 5,
			},
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "galena-refining",
		icon = "__base__/graphics/icons/coal.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 8,
		ingredients = { { "galena-ore", 10 } },
		results = {
			{
				name = "lead-ore",
				probability = 1,
				amount = 5,
			},
			{
				name = "tin-ore",
				probability = 1,
				amount = 5,
			},
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "carbonatite-refining",
		icon = "__base__/graphics/icons/coal.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 8,
		ingredients = {{"carbonatite-ore", 10}},
		results =
		{
		  {
			name = "scarce-metal-ores",
			probability = 1,
			amount = 2,
		  },
		  {
			name = "valuable-metal-ores",
			probability = 1,
			amount = 8
		  }
		},
		icon_size = 64
	},
	{
		type = "recipe",
		name = "valuable-pyrorecycling",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/valuable-metals.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 1,
		ingredients = { { "valuable-metal-ores", 8 }, {"sulfur", 4}, {"coal", 2} },
		results = {
			{ "carbonatite-ore", 8 },
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "alloy-furnace",
		icon = "__base__/graphics/icons/electric-furnace.png",
		category = "crafting",
		subgroup = "sam-recipes",
		enabled = true,
		energy_required = 12,
		ingredients = { { "cobalt-plate", 10 }, { "nickel-plate", 10 }, { "iron-plate", 10 }, { "stone-brick", 25 } },
		results = {
			{ "alloy-furnace", 1 },
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "advanced-alloy-furnace",
		icon = "__base__/graphics/icons/electric-furnace.png",
		category = "crafting",
		subgroup = "sam-recipes",
		enabled = true,
		energy_required = 36,
		ingredients = { { "havar-plate", 10 }, { "invar-plate", 10 }, { "steel-plate", 30 }, { "advanced-circuit", 25 } },
		results = {
			{ "advanced-alloy-furnace", 1 },
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "chemical-refinery",
		icon = "__base__/graphics/icons/oil-refinery.png",
		category = "crafting",
		subgroup = "sam-recipes",
		enabled = true,
		energy_required = 12,
		ingredients = { { "duralumin-plate", 30 }, { "kovar-plate", 10 }, { "titanium-plate", 20 }, { "concrete", 50 } },
		results = {
			{ "chemical-refinery", 1 },
		},
		icon_size = 64,
	},
	--Nickel Creation
	{
		type = "recipe",
		name = "limonite-ore",
		category = "chemistry",
		subgroup = "metallurgy-processes",
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/thorium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "magnetite-ore", 4 },
			{ "haematite-ore", 4 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		result = "limonite-ore",
		result_count = 8,
	},
	{
		type = "recipe",
		name = "nickel-reduction",
		category = "crafting",
		subgroup = "metallurgy-processes",
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "limonite-ore", 4 },
		},
		result = "nickel-ore",
		result_count = 8,
	},
	--Metallurgy Stages
	--Magnetite Refining
	{
		type = "recipe",
		name = "magnetite-rock",
		category = "crafting",
		main_product = "magnetite-rock",
		hide_from_player_crafting = true,
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-rock.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "magnetite-ore", 4 },
		},
		results = {
			{
				name = "magnetite-rock",
				probability = 1,
				amount = 2,
			},
			{
				name = "magnetite-rock",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "magnetite-chunk",
		category = "alloy-smelting",
		main_product = "magnetite-chunk",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-chunk.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "magnetite-rock", 2 },
			{ "sulfur", 1 },
		},
		results = {
			{
				name = "magnetite-chunk",
				probability = 1,
				amount = 2,
			},
			{
				name = "magnetite-chunk",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "crushed-magnetite",
		category = "basic-crafting",
		main_product = "crushed-magnetite",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-crushed.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "magnetite-chunk", 2 },
		},
		results = {
			{
				name = "crushed-magnetite",
				probability = 1,
				amount = 2,
			},
			{
				name = "crushed-magnetite",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-magnetite-ore",
		category = "chemistry",
		main_product = "refined-magnetite-ore",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-refined.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "crushed-magnetite", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "sulfuric-acid", amount = 10 },
		},
		results = {
			{
				name = "refined-magnetite-ore",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-magnetite-ore",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "magnetite-slurry",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 8,
		enabled = true,
		ingredients = {
			{ "refined-magnetite-ore", 4 },
		},
		results = {
			{ type = "fluid", name = "magnetite-slurry", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "magnetite-shard",
		category = "chemistry",
		main_product = "magnetite-shard",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "magnetite-slurry", amount = 40 },
		},
		results = {
			{
				name = "magnetite-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "magnetite-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-magnetite-shard",
		category = "chemistry",
		main_product = "purified-magnetite-shard",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "magnetite-shard", 2 },
			{ type = "fluid", name = "water", amount = 25 },
			{ type = "fluid", name = "carbonic-acid", amount = 10 },
		},
		results = {
			{
				name = "purified-magnetite-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "purified-magnetite-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-magnetite-ore-chemical",
		category = "chemistry",
		main_product = "imperfect-magnetite",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "purified-magnetite-shard", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "caudic-acid", amount = 10 },
		},
		results = {
			{
				name = "imperfect-magnetite",
				probability = 1,
				amount = 2,
			},
			{
				name = "imperfect-magnetite",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "magnetite-powder",
		category = "crafting",
		main_product = "magnetite-powder",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "imperfect-magnetite", 2 },
		},
		results = {
			{
				name = "magnetite-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "magnetite-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "refined-magnetite-powder",
		category = "chemistry",
		main_product = "refined-magnetite-powder",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "magnetite-powder", 2 },
			{ type = "fluid", name = "water", amount = 25 },
		},
		results = {
			{
				name = "refined-magnetite-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-magnetite-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-magnetite-powder",
		category = "chemistry",
		main_product = "pure-magnetite-powder",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "refined-magnetite-powder", 2 },
			{ type = "fluid", name = "dilute-acid-solution", amount = 10 },
		},
		results = {
			{
				name = "pure-magnetite-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "pure-magnetite-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-magnetite-ore-powder",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/magnetite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "pure-magnetite-powder", 1 },
			{ type = "fluid", name = "steam", amount = 10 },
			{ type = "fluid", name = "acid-cleaning-solution", amount = 10 },
		},
		result = "pure-magnetite-ore",
		result_count = 3,
	},

	--Malachite Refining
	{
		type = "recipe",
		name = "malachite-rock",
		category = "crafting",
		main_product = "malachite-rock",
		hide_from_player_crafting = true,
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-rock.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "malachite-ore", 4 },
		},
		results = {
			{
				name = "malachite-rock",
				probability = 1,
				amount = 2,
			},
			{
				name = "malachite-rock",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "malachite-chunk",
		category = "alloy-smelting",
		main_product = "malachite-chunk",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-chunk.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "malachite-rock", 2 },
			{ "sulfur", 1 },
		},
		results = {
			{
				name = "malachite-chunk",
				probability = 1,
				amount = 2,
			},
			{
				name = "malachite-chunk",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "crushed-malachite",
		category = "basic-crafting",
		main_product = "crushed-malachite",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-crushed.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "malachite-chunk", 2 },
		},
		results = {
			{
				name = "crushed-malachite",
				probability = 1,
				amount = 2,
			},
			{
				name = "crushed-malachite",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-malachite-ore",
		category = "chemistry",
		main_product = "refined-malachite-ore",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-refined.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "crushed-malachite", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "sulfuric-acid", amount = 10 },
		},
		results = {
			{
				name = "refined-malachite-ore",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-malachite-ore",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "malachite-slurry",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 8,
		enabled = true,
		ingredients = {
			{ "refined-malachite-ore", 4 },
		},
		results = {
			{ type = "fluid", name = "malachite-slurry", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "malachite-shard",
		category = "chemistry",
		main_product = "malachite-shard",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "malachite-slurry", amount = 40 },
		},
		results = {
			{
				name = "malachite-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "malachite-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-malachite-shard",
		category = "chemistry",
		main_product = "purified-malachite-shard",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "malachite-shard", 2 },
			{ type = "fluid", name = "water", amount = 25 },
			{ type = "fluid", name = "chloric-acid", amount = 10 },
		},
		results = {
			{
				name = "purified-malachite-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "purified-malachite-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-malachite-ore-chemical",
		category = "chemistry",
		main_product = "imperfect-malachite",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "purified-malachite-shard", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "luret-acid", amount = 10 },
		},
		results = {
			{
				name = "imperfect-malachite",
				probability = 1,
				amount = 2,
			},
			{
				name = "imperfect-malachite",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "malachite-powder",
		category = "crafting",
		main_product = "malachite-powder",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "imperfect-malachite", 2 },
		},
		results = {
			{
				name = "malachite-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "malachite-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "refined-malachite-powder",
		category = "chemistry",
		main_product = "refined-malachite-powder",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "malachite-powder", 2 },
			{ type = "fluid", name = "water", amount = 25 },
		},
		results = {
			{
				name = "refined-malachite-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-malachite-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-malachite-powder",
		category = "chemistry",
		main_product = "pure-malachite-powder",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "refined-malachite-powder", 2 },
			{ type = "fluid", name = "dilute-acid-solution", amount = 10 },
		},
		results = {
			{
				name = "pure-malachite-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "pure-malachite-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-malachite-ore-powder",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/malachite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "pure-malachite-powder", 1 },
			{ type = "fluid", name = "steam", amount = 10 },
			{ type = "fluid", name = "acid-cleaning-solution", amount = 10 },
		},
		result = "pure-malachite-ore",
		result_count = 3,
	},

	--Nickel Refining
	{
		type = "recipe",
		name = "nickel-rock",
		category = "crafting",
		main_product = "nickel-rock",
		hide_from_player_crafting = true,
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-rock.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "nickel-ore", 4 },
		},
		results = {
			{
				name = "nickel-rock",
				probability = 1,
				amount = 2,
			},
			{
				name = "nickel-rock",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "nickel-chunk",
		category = "alloy-smelting",
		main_product = "nickel-chunk",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-chunk.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "nickel-rock", 2 },
			{ "sulfur", 1 },
		},
		results = {
			{
				name = "nickel-chunk",
				probability = 1,
				amount = 2,
			},
			{
				name = "nickel-chunk",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "crushed-nickel",
		category = "basic-crafting",
		main_product = "crushed-nickel",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-crushed.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "nickel-chunk", 2 },
		},
		results = {
			{
				name = "crushed-nickel",
				probability = 1,
				amount = 2,
			},
			{
				name = "crushed-nickel",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-nickel-ore",
		category = "chemistry",
		main_product = "refined-nickel-ore",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-refined.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "crushed-nickel", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "nitric-acid", amount = 10 },
		},
		results = {
			{
				name = "refined-nickel-ore",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-nickel-ore",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "nickel-slurry",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 8,
		enabled = true,
		ingredients = {
			{ "refined-nickel-ore", 4 },
		},
		results = {
			{ type = "fluid", name = "nickel-slurry", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "nickel-shard",
		category = "chemistry",
		main_product = "nickel-shard",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "nickel-slurry", amount = 40 },
		},
		results = {
			{
				name = "nickel-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "nickel-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-nickel-shard",
		category = "chemistry",
		main_product = "purified-nickel-shard",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "nickel-shard", 2 },
			{ type = "fluid", name = "water", amount = 25 },
			{ type = "fluid", name = "azane-acid", amount = 10 },
		},
		results = {
			{
				name = "purified-nickel-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "purified-nickel-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-nickel-ore-chemical",
		category = "chemistry",
		main_product = "imperfect-nickel",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "purified-nickel-shard", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "vixal-acid", amount = 10 },
		},
		results = {
			{
				name = "imperfect-nickel",
				probability = 1,
				amount = 2,
			},
			{
				name = "imperfect-nickel",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "nickel-powder",
		category = "crafting",
		main_product = "nickel-powder",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "imperfect-nickel", 2 },
		},
		results = {
			{
				name = "nickel-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "nickel-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "refined-nickel-powder",
		category = "chemistry",
		main_product = "refined-nickel-powder",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "nickel-powder", 2 },
			{ type = "fluid", name = "water", amount = 25 },
		},
		results = {
			{
				name = "refined-nickel-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-nickel-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-nickel-powder",
		category = "chemistry",
		main_product = "pure-nickel-powder",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "refined-nickel-powder", 2 },
			{ type = "fluid", name = "dilute-acid-solution", amount = 10 },
		},
		results = {
			{
				name = "pure-nickel-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "pure-nickel-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-nickel-ore-powder",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/nickel-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "pure-nickel-powder", 1 },
			{ type = "fluid", name = "steam", amount = 10 },
			{ type = "fluid", name = "acid-cleaning-solution", amount = 10 },
		},
		result = "pure-nickel-ore",
		result_count = 3,
	},

	--Cobalt Refining
	{
		type = "recipe",
		name = "cobalt-rock",
		category = "crafting",
		main_product = "cobalt-rock",
		hide_from_player_crafting = true,
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-rock.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "cobalt-ore", 4 },
		},
		results = {
			{
				name = "cobalt-rock",
				probability = 1,
				amount = 2,
			},
			{
				name = "cobalt-rock",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "cobalt-chunk",
		category = "alloy-smelting",
		main_product = "cobalt-chunk",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-chunk.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "cobalt-rock", 2 },
			{ "sulfur", 1 },
		},
		results = {
			{
				name = "cobalt-chunk",
				probability = 1,
				amount = 2,
			},
			{
				name = "cobalt-chunk",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "crushed-cobalt",
		category = "basic-crafting",
		main_product = "crushed-cobalt",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-crushed.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "cobalt-chunk", 2 },
		},
		results = {
			{
				name = "crushed-cobalt",
				probability = 1,
				amount = 2,
			},
			{
				name = "crushed-cobalt",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-cobalt-ore",
		category = "chemistry",
		main_product = "refined-cobalt-ore",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-refined.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "crushed-cobalt", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "muriatic-acid", amount = 10 },
		},
		results = {
			{
				name = "refined-cobalt-ore",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-cobalt-ore",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "cobalt-slurry",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 8,
		enabled = true,
		ingredients = {
			{ "refined-cobalt-ore", 4 },
		},
		results = {
			{ type = "fluid", name = "cobalt-slurry", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "cobalt-shard",
		category = "chemistry",
		main_product = "cobalt-shard",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "cobalt-slurry", amount = 40 },
		},
		results = {
			{
				name = "cobalt-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "cobalt-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-cobalt-shard",
		category = "chemistry",
		main_product = "purified-cobalt-shard",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "cobalt-shard", 2 },
			{ type = "fluid", name = "water", amount = 25 },
			{ type = "fluid", name = "nitric-acid", amount = 10 },
		},
		results = {
			{
				name = "purified-cobalt-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "purified-cobalt-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-cobalt-ore-chemical",
		category = "chemistry",
		main_product = "imperfect-cobalt",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "purified-cobalt-shard", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "azane-acid", amount = 10 },
		},
		results = {
			{
				name = "imperfect-cobalt",
				probability = 1,
				amount = 2,
			},
			{
				name = "imperfect-cobalt",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "cobalt-powder",
		category = "crafting",
		main_product = "cobalt-powder",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "imperfect-cobalt", 2 },
		},
		results = {
			{
				name = "cobalt-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "cobalt-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "refined-cobalt-powder",
		category = "chemistry",
		main_product = "refined-cobalt-powder",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "cobalt-powder", 2 },
			{ type = "fluid", name = "water", amount = 25 },
		},
		results = {
			{
				name = "refined-cobalt-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-cobalt-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-cobalt-powder",
		category = "chemistry",
		main_product = "pure-cobalt-powder",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "refined-cobalt-powder", 2 },
			{ type = "fluid", name = "dilute-acid-solution", amount = 10 },
		},
		results = {
			{
				name = "pure-cobalt-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "pure-cobalt-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-cobalt-ore-powder",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "pure-cobalt-powder", 1 },
			{ type = "fluid", name = "steam", amount = 10 },
			{ type = "fluid", name = "acid-cleaning-solution", amount = 10 },
		},
		result = "pure-cobalt-ore",
		result_count = 3,
	},

	--Aluminum Refining
	{
		type = "recipe",
		name = "aluminum-rock",
		category = "crafting",
		main_product = "aluminum-rock",
		hide_from_player_crafting = true,
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-rock.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "aluminum-ore", 4 },
		},
		results = {
			{
				name = "aluminum-rock",
				probability = 1,
				amount = 2,
			},
			{
				name = "aluminum-rock",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "aluminum-chunk",
		category = "alloy-smelting",
		main_product = "aluminum-chunk",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-chunk.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "aluminum-rock", 2 },
			{ "sulfur", 1 },
		},
		results = {
			{
				name = "aluminum-chunk",
				probability = 1,
				amount = 2,
			},
			{
				name = "aluminum-chunk",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "crushed-aluminum",
		category = "basic-crafting",
		main_product = "crushed-aluminum",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-crushed.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "aluminum-chunk", 2 },
		},
		results = {
			{
				name = "crushed-aluminum",
				probability = 1,
				amount = 2,
			},
			{
				name = "crushed-aluminum",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-aluminum-ore",
		category = "chemistry",
		main_product = "refined-aluminum-ore",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-refined.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "crushed-aluminum", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "chloric-acid", amount = 10 },
		},
		results = {
			{
				name = "refined-aluminum-ore",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-aluminum-ore",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "aluminum-slurry",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 8,
		enabled = true,
		ingredients = {
			{ "refined-aluminum-ore", 4 },
		},
		results = {
			{ type = "fluid", name = "aluminum-slurry", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "aluminum-shard",
		category = "chemistry",
		main_product = "aluminum-shard",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "aluminum-slurry", amount = 40 },
		},
		results = {
			{
				name = "aluminum-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "aluminum-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-aluminum-shard",
		category = "chemistry",
		main_product = "purified-aluminum-shard",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "aluminum-shard", 2 },
			{ type = "fluid", name = "water", amount = 25 },
			{ type = "fluid", name = "muriatic-acid", amount = 10 },
		},
		results = {
			{
				name = "purified-aluminum-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "purified-aluminum-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-aluminum-ore-chemical",
		category = "chemistry",
		main_product = "imperfect-aluminum",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "purified-aluminum-shard", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "verelic-acid", amount = 10 },
		},
		results = {
			{
				name = "imperfect-aluminum",
				probability = 1,
				amount = 2,
			},
			{
				name = "imperfect-aluminum",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "aluminum-powder",
		category = "crafting",
		main_product = "aluminum-powder",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "imperfect-aluminum", 2 },
		},
		results = {
			{
				name = "aluminum-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "aluminum-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "refined-aluminum-powder",
		category = "chemistry",
		main_product = "refined-aluminum-powder",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "aluminum-powder", 2 },
			{ type = "fluid", name = "water", amount = 25 },
		},
		results = {
			{
				name = "refined-aluminum-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-aluminum-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-aluminum-powder",
		category = "chemistry",
		main_product = "pure-aluminum-powder",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "refined-aluminum-powder", 2 },
			{ type = "fluid", name = "dilute-acid-solution", amount = 10 },
		},
		results = {
			{
				name = "pure-aluminum-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "pure-aluminum-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-aluminum-ore-powder",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "pure-aluminum-powder", 1 },
			{ type = "fluid", name = "steam", amount = 10 },
			{ type = "fluid", name = "acid-cleaning-solution", amount = 10 },
		},
		result = "pure-aluminum-ore",
		result_count = 3,
	},

	-- Titanium Creation
	{
		type = "recipe",
		name = "ilmenite-ore",
		category = "chemistry",
		subgroup = "metallurgy-processes",
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/thorium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "magnetite-ore", 2 },
			{ "titanium-ore", 6 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		result = "ilmenite-ore",
		result_count = 8,
	},
	{
		type = "recipe",
		name = "titanium-reduction",
		category = "crafting",
		subgroup = "metallurgy-processes",
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/thorium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "ilmenite-ore", 4 },
		},
		result = "titanium-ore",
		result_count = 8,
	},
	--Titanium Refining
	{
		type = "recipe",
		name = "titanium-rock",
		category = "crafting",
		main_product = "titanium-rock",
		hide_from_player_crafting = true,
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-rock.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "titanium-ore", 4 },
		},
		results = {
			{
				name = "titanium-rock",
				probability = 1,
				amount = 2,
			},
			{
				name = "titanium-rock",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "titanium-chunk",
		category = "alloy-smelting",
		main_product = "titanium-chunk",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-chunk.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "titanium-rock", 2 },
			{ "sulfur", 1 },
		},
		results = {
			{
				name = "titanium-chunk",
				probability = 1,
				amount = 2,
			},
			{
				name = "titanium-chunk",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "crushed-titanium",
		category = "basic-crafting",
		main_product = "crushed-titanium",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-crushed.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "titanium-chunk", 2 },
		},
		results = {
			{
				name = "crushed-titanium",
				probability = 1,
				amount = 2,
			},
			{
				name = "crushed-titanium",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-titanium-ore",
		category = "chemistry",
		main_product = "refined-titanium-ore",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-refined.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "crushed-titanium", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "muriatic-acid", amount = 10 },
		},
		results = {
			{
				name = "refined-titanium-ore",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-titanium-ore",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "titanium-slurry",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 8,
		enabled = true,
		ingredients = {
			{ "refined-titanium-ore", 4 },
		},
		results = {
			{ type = "fluid", name = "titanium-slurry", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "titanium-shard",
		category = "chemistry",
		main_product = "titanium-shard",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "titanium-slurry", amount = 40 },
		},
		results = {
			{
				name = "titanium-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "titanium-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-titanium-shard",
		category = "chemistry",
		main_product = "purified-titanium-shard",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "titanium-shard", 2 },
			{ type = "fluid", name = "water", amount = 25 },
			{ type = "fluid", name = "carbonic-acid", amount = 10 },
		},
		results = {
			{
				name = "purified-titanium-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "purified-titanium-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-titanium-ore-chemical",
		category = "chemistry",
		main_product = "imperfect-titanium",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "purified-titanium-shard", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "genhal-acid", amount = 10 },
		},
		results = {
			{
				name = "imperfect-titanium",
				probability = 1,
				amount = 2,
			},
			{
				name = "imperfect-titanium",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "titanium-powder",
		category = "crafting",
		main_product = "titanium-powder",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "imperfect-titanium", 2 },
		},
		results = {
			{
				name = "titanium-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "titanium-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "refined-titanium-powder",
		category = "chemistry",
		main_product = "refined-titanium-powder",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "titanium-powder", 2 },
			{ type = "fluid", name = "water", amount = 25 },
		},
		results = {
			{
				name = "refined-titanium-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-titanium-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-titanium-powder",
		category = "chemistry",
		main_product = "pure-titanium-powder",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "refined-titanium-powder", 2 },
			{ type = "fluid", name = "dilute-acid-solution", amount = 10 },
		},
		results = {
			{
				name = "pure-titanium-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "pure-titanium-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-titanium-ore-powder",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/titanium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "pure-titanium-powder", 1 },
			{ type = "fluid", name = "steam", amount = 10 },
			{ type = "fluid", name = "acid-cleaning-solution", amount = 10 },
		},
		result = "pure-titanium-ore",
		result_count = 3,
	},

	--Chromite Refining
	{
		type = "recipe",
		name = "chromite-rock",
		category = "crafting",
		main_product = "chromite-rock",
		hide_from_player_crafting = true,
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-rock.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "chromite-ore", 4 },
		},
		results = {
			{
				name = "chromite-rock",
				probability = 1,
				amount = 2,
			},
			{
				name = "chromite-rock",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "chromite-chunk",
		category = "alloy-smelting",
		main_product = "chromite-chunk",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-chunk.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "chromite-rock", 2 },
			{ "sulfur", 1 },
		},
		results = {
			{
				name = "chromite-chunk",
				probability = 1,
				amount = 2,
			},
			{
				name = "chromite-chunk",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "crushed-chromite",
		category = "basic-crafting",
		main_product = "crushed-chromite",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-crushed.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "chromite-chunk", 2 },
		},
		results = {
			{
				name = "crushed-chromite",
				probability = 1,
				amount = 2,
			},
			{
				name = "crushed-chromite",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-chromite-ore",
		category = "chemistry",
		main_product = "refined-chromite-ore",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-refined.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "crushed-chromite", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "carbonic-acid", amount = 10 },
		},
		results = {
			{
				name = "refined-chromite-ore",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-chromite-ore",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "chromite-slurry",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 8,
		enabled = true,
		ingredients = {
			{ "refined-chromite-ore", 4 },
		},
		results = {
			{ type = "fluid", name = "chromium-slurry", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "chromite-shard",
		category = "chemistry",
		main_product = "chromite-shard",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "chromium-slurry", amount = 40 },
		},
		results = {
			{
				name = "chromite-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "chromite-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-chromite-shard",
		category = "chemistry",
		main_product = "purified-chromite-shard",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "chromite-shard", 2 },
			{ type = "fluid", name = "water", amount = 25 },
			{ type = "fluid", name = "azane-acid", amount = 10 },
		},
		results = {
			{
				name = "purified-chromite-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "purified-chromite-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-chromite-ore-chemical",
		category = "chemistry",
		main_product = "imperfect-chromite",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "purified-chromite-shard", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "buren-acid", amount = 10 },
		},
		results = {
			{
				name = "imperfect-chromite",
				probability = 1,
				amount = 2,
			},
			{
				name = "imperfect-chromite",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "chromite-powder",
		category = "crafting",
		main_product = "chromite-powder",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "imperfect-chromite", 2 },
		},
		results = {
			{
				name = "chromite-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "chromite-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "refined-chromite-powder",
		category = "chemistry",
		main_product = "refined-chromite-powder",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "chromite-powder", 2 },
			{ type = "fluid", name = "water", amount = 25 },
		},
		results = {
			{
				name = "refined-chromite-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-chromite-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-chromite-powder",
		category = "chemistry",
		main_product = "pure-chromite-powder",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "refined-chromite-powder", 2 },
			{ type = "fluid", name = "dilute-acid-solution", amount = 10 },
		},
		results = {
			{
				name = "pure-chromite-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "pure-chromite-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-chromite-ore-powder",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/chromite-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "pure-chromite-powder", 1 },
			{ type = "fluid", name = "steam", amount = 10 },
			{ type = "fluid", name = "acid-cleaning-solution", amount = 10 },
		},
		result = "pure-chromite-ore",
		result_count = 3,
	},

	--Lead Refining
	{
		type = "recipe",
		name = "lead-rock",
		category = "crafting",
		main_product = "lead-rock",
		hide_from_player_crafting = true,
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-rock.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "lead-ore", 4 },
		},
		results = {
			{
				name = "lead-rock",
				probability = 1,
				amount = 2,
			},
			{
				name = "lead-rock",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "lead-chunk",
		category = "alloy-smelting",
		main_product = "lead-chunk",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-chunk.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "lead-rock", 2 },
			{ "sulfur", 1 },
		},
		results = {
			{
				name = "lead-chunk",
				probability = 1,
				amount = 2,
			},
			{
				name = "lead-chunk",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "crushed-lead",
		category = "basic-crafting",
		main_product = "crushed-lead",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-crushed.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "lead-chunk", 2 },
		},
		results = {
			{
				name = "crushed-lead",
				probability = 1,
				amount = 2,
			},
			{
				name = "crushed-lead",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-lead-ore",
		category = "chemistry",
		main_product = "refined-lead-ore",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-refined.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "crushed-lead", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "muriatic-acid", amount = 10 },
		},
		results = {
			{
				name = "refined-lead-ore",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-lead-ore",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "lead-slurry",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 8,
		enabled = true,
		ingredients = {
			{ "refined-lead-ore", 4 },
		},
		results = {
			{ type = "fluid", name = "lead-slurry", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "lead-shard",
		category = "chemistry",
		main_product = "lead-shard",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "lead-slurry", amount = 40 },
		},
		results = {
			{
				name = "lead-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "lead-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-lead-shard",
		category = "chemistry",
		main_product = "purified-lead-shard",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "lead-shard", 2 },
			{ type = "fluid", name = "water", amount = 25 },
			{ type = "fluid", name = "chloric-acid", amount = 10 },
		},
		results = {
			{
				name = "purified-lead-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "purified-lead-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-lead-ore-chemical",
		category = "chemistry",
		main_product = "imperfect-lead",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "purified-lead-shard", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "vixal-acid", amount = 10 },
		},
		results = {
			{
				name = "imperfect-lead",
				probability = 1,
				amount = 2,
			},
			{
				name = "imperfect-lead",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "lead-powder",
		category = "crafting",
		main_product = "lead-powder",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "imperfect-lead", 2 },
		},
		results = {
			{
				name = "lead-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "lead-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "refined-lead-powder",
		category = "chemistry",
		main_product = "refined-lead-powder",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "lead-powder", 2 },
			{ type = "fluid", name = "water", amount = 25 },
		},
		results = {
			{
				name = "refined-lead-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-lead-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-lead-powder",
		category = "chemistry",
		main_product = "pure-lead-powder",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "refined-lead-powder", 2 },
			{ type = "fluid", name = "dilute-acid-solution", amount = 10 },
		},
		results = {
			{
				name = "pure-lead-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "pure-lead-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-lead-ore-powder",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/lead-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "pure-lead-powder", 1 },
			{ type = "fluid", name = "steam", amount = 10 },
			{ type = "fluid", name = "acid-cleaning-solution", amount = 10 },
		},
		result = "pure-lead-ore",
		result_count = 3,
	},

	--Tin Refining
	{
		type = "recipe",
		name = "tin-rock",
		category = "crafting",
		main_product = "tin-rock",
		hide_from_player_crafting = true,
		order = "aa",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-rock.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "tin-ore", 4 },
		},
		results = {
			{
				name = "tin-rock",
				probability = 1,
				amount = 2,
			},
			{
				name = "tin-rock",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "tin-chunk",
		category = "alloy-smelting",
		main_product = "tin-chunk",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-chunk.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "tin-rock", 2 },
			{ "sulfur", 1 },
		},
		results = {
			{
				name = "tin-chunk",
				probability = 1,
				amount = 2,
			},
			{
				name = "tin-chunk",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "crushed-tin",
		category = "basic-crafting",
		main_product = "crushed-tin",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-crushed.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "tin-chunk", 2 },
		},
		results = {
			{
				name = "crushed-tin",
				probability = 1,
				amount = 2,
			},
			{
				name = "crushed-tin",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-tin-ore",
		category = "chemistry",
		main_product = "refined-tin-ore",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-refined.png",
		icon_size = 32,
		icon_mipmaps = 4,
		energy_required = 2,
		enabled = true,
		ingredients = {
			{ "crushed-tin", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "carbonic-acid", amount = 10 },
		},
		results = {
			{
				name = "refined-tin-ore",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-tin-ore",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "tin-slurry",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 8,
		enabled = true,
		ingredients = {
			{ "refined-tin-ore", 4 },
		},
		results = {
			{ type = "fluid", name = "tin-slurry", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "tin-shard",
		category = "chemistry",
		main_product = "tin-shard",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "tin-slurry", amount = 40 },
		},
		results = {
			{
				name = "tin-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "tin-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-tin-shard",
		category = "chemistry",
		main_product = "purified-tin-shard",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "tin-shard", 2 },
			{ type = "fluid", name = "water", amount = 25 },
			{ type = "fluid", name = "azane-acid", amount = 10 },
		},
		results = {
			{
				name = "purified-tin-shard",
				probability = 1,
				amount = 2,
			},
			{
				name = "purified-tin-shard",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-tin-ore-chemical",
		category = "chemistry",
		main_product = "imperfect-tin",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "purified-tin-shard", 2 },
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "fluid", name = "luret-acid", amount = 10 },
		},
		results = {
			{
				name = "imperfect-tin",
				probability = 1,
				amount = 2,
			},
			{
				name = "imperfect-tin",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "tin-powder",
		category = "crafting",
		main_product = "tin-powder",
		hide_from_player_crafting = true,
		order = "ab",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "imperfect-tin", 2 },
		},
		results = {
			{
				name = "tin-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "tin-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "refined-tin-powder",
		category = "chemistry",
		main_product = "refined-tin-powder",
		hide_from_player_crafting = true,
		order = "ac",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "tin-powder", 2 },
			{ type = "fluid", name = "water", amount = 25 },
		},
		results = {
			{
				name = "refined-tin-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "refined-tin-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-tin-powder",
		category = "chemistry",
		main_product = "pure-tin-powder",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "refined-tin-powder", 2 },
			{ type = "fluid", name = "dilute-acid-solution", amount = 10 },
		},
		results = {
			{
				name = "pure-tin-powder",
				probability = 1,
				amount = 2,
			},
			{
				name = "pure-tin-powder",
				probability = 0.5,
				amount = 1,
			},
		}
	},
	{
		type = "recipe",
		name = "pure-tin-ore-powder",
		category = "chemistry",
		hide_from_player_crafting = true,
		order = "ad",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/tin-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ "pure-tin-powder", 1 },
			{ type = "fluid", name = "steam", amount = 10 },
			{ type = "fluid", name = "acid-cleaning-solution", amount = 10 },
		},
		result = "pure-tin-ore",
		result_count = 3,
	},

	--Thorium Refining
	{
		type = "recipe",
		name = "thorium-nuclear-decay",
		energy_required = 30,
		enabled = true,
		category = "centrifuging",
		ingredients = {
			{ "thorium-ore", 50 },
			{ "uranium-235", 1 },
		},
		icon = "__base__/graphics/icons/nuclear-fuel-reprocessing.png",
		icon_size = 64,
		icon_mipmaps = 4,
		subgroup = "metallurgy-processes",
		order = "r[uranium-processing]-b[nuclear-fuel-reprocessing]",
		main_product = "",
		results = { { "uranium-238", 50 } },
		allow_decomposition = false,
	},
	--Samarium Refining

	--Neodymium Refining

	--New Items (Nuclear)
	{
		type = "recipe",
		name = "thorium-fuel-cell",
		subgroup = "sam-recipes",
		energy_required = 50,
		enabled = true,
		ingredients = {
			{ "monel-plate", 30 },
			{ "invar-plate", 30 },
			{ "kovar-plate", 60 },
			{ "thorium-ore", 50 },
			{ "uranium-235", 1 },
			{ "uranium-238", 10 },
		},
		result = "thorium-fuel-cell",
		result_count = 10,
	},
	{
		type = "recipe",
		name = "uranium-233-cell",
		subgroup = "sam-recipes",
		energy_required = 100,
		enabled = true,
		ingredients = {
			{ "titanium5-plate", 20 },
			{ "havar-plate", 20 },
			{ "incoloy-plate", 40 },
			{ "uranium-233", 1 },
			{ "uranium-238", 50 },
		},
		result = "uranium-233-cell",
		result_count = 20,
	},
	{
		type = "recipe",
		name = "thorium-fuel-reprocessing",
		energy_required = 10,
		enabled = true,
		category = "centrifuging",
		ingredients = { { "used-up-thorium-fuel-cell", 1 } },
		icon = "__base__/graphics/icons/nuclear-fuel-reprocessing.png",
		icon_size = 64,
		icon_mipmaps = 4,
		subgroup = "metallurgy-processes",
		order = "r[uranium-processing]-b[nuclear-fuel-reprocessing]",
		main_product = "",
		results = { { "uranium-233", 4 } },
		allow_decomposition = false,
	},

	--Magnetic Age

	--Oil related Age
	{
		type = "recipe",
		name = "oil-shale-refining",
		icon = "__base__/graphics/icons/fluid/coal-liquefaction.png",
		category = "oil-processing",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 5,
		ingredients = { { "oil-shale-ore", 1 }, { type = "fluid", name = "steam", amount = 100 } },
		results = { --other resources include aluminum, magnesium, silicon - Check Oil Shale
			{
				name = "stone-debris",
				amount = 20,
			},
			{
				type = "fluid",
				name = "chemical-oil",
				amount = 100,
			},
			{
				name = "sulfur",
				probability = 0.1,
				amount = 4,
			},
			{
				name = "coal",
				probability = 0.4,
				amount = 10,
			},
		},
		icon_size = 64,
	},

	--Recycle Ores
	{
		type = "recipe",
		name = "decaying-matter-cell",
		icon = "__base__/graphics/icons/used-up-uranium-fuel-cell.png",
		category = "crafting",
		subgroup = "sam-recipes",
		enabled = true,
		energy_required = 10,
		ingredients = {
			{ "used-up-uranium-fuel-cell", 1 },
			{ "thorium-ore", 20 },
			{ "havar-plate", 10 },
			{ "kovar-plate", 20 },
			{ "duralumin-plate", 20 },
		},
		result = "decaying-matter-cell",
		result_count = 10,
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "aluminum-transmutation",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/aluminum-ore.png",
		category = "centrifuging",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 300,
		ingredients = { { "decaying-matter-cell", 1 }, { "aluminum-ore", 2000 } },
		results = {
			{ "used-up-uranium-fuel-cell", 1 },
			{
				name = "titanium-ore",
				probability = 1,
				amount_min = 100,
				amount_max = 500,
			},
			{
				name = "bauxite-ore",
				probability = 1,
				amount_min = 100,
				amount_max = 500,
			},
			{
				name = "laterite-ore",
				probability = 1,
				amount_min = 200,
				amount_max = 1000,
			},
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "cobalt-transmutation",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobalt-ore.png",
		category = "centrifuging",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 300,
		ingredients = { { "decaying-matter-cell", 1 }, { "cobalt-ore", 2000 } },
		results = {
			{ "used-up-uranium-fuel-cell", 1 },
			{
				name = "nickel-ore",
				probability = 1,
				amount_min = 100,
				amount_max = 500,
			},
			{
				name = "cobaltite-ore",
				probability = 1,
				amount_min = 100,
				amount_max = 500,
			},
			{
				name = "laterite-ore",
				probability = 1,
				amount_min = 200,
				amount_max = 1000,
			},
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "samarium-transmutation",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/samarium-ore.png",
		category = "centrifuging",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 300,
		ingredients = { { "decaying-matter-cell", 1 }, { "samarium-ore", 2000 } },
		results = {
			{ "used-up-uranium-fuel-cell", 1 },
			{
				name = "uranium-ore",
				probability = 1,
				amount_min = 100,
				amount_max = 500,
			},
			{
				name = "thorium-ore",
				probability = 1,
				amount_min = 100,
				amount_max = 500,
			},
			{
				name = "monazite-ore",
				probability = 1,
				amount_min = 200,
				amount_max = 1000,
			},
		},
		catalyst_amount = "used-up-uranium-fuel-cell", 1,
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "neodymium-transmutation",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/neodymium-ore.png",
		category = "centrifuging",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 300,
		ingredients = { { "decaying-matter-cell", 1 }, { "neodymium-ore", 2000 } },
		results = {
			{ "used-up-uranium-fuel-cell", 1 },
			{
				name = "uranium-ore",
				probability = 1,
				amount_min = 100,
				amount_max = 500,
			},
			{
				name = "thorium-ore",
				probability = 1,
				amount_min = 100,
				amount_max = 500,
			},
			{
				name = "monazite-ore",
				probability = 1,
				amount_min = 200,
				amount_max = 1000,
			},
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "bauxite-recycling",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/bauxite-ore.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 1,
		ingredients = { { "bauxite-ore", 8 } },
		results = {
			{ "laterite-ore", 8 },
		},
		icon_size = 64,
	},
	{
		type = "recipe",
		name = "cobaltite-recycling",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/cobaltite-ore.png",
		category = "crafting",
		subgroup = "metallurgy-processes",
		enabled = true,
		energy_required = 1,
		ingredients = { { "cobaltite-ore", 8 } },
		results = {
			{ "laterite-ore", 8 },
		},
		icon_size = 64,
	},
	{

		type = "recipe",
		name = "bulk-drone",
		icon = "__Sky-Atlas-Metallurgy-Rebirth__/graphics/icons/construction-robo-ico.png",
		category = "advanced-crafting",
		subgroup = "logistic-network",
		enabled = true,
		energy_required = 20,
		ingredients = {
			{ "titanium-plate", 8 },
			{ "kovar-plate", 10 },
			{ "bronze-plate", 25 },
			{ "logistic-robot", 4 },
			{ "accumulator", 1 },
		},
		results = {
			{ "bulk-drone", 1 },
		},
		icon_size = 32,
	},
	{
		type = "recipe",
		name = "stone-reprocessing",
		energy_required = 20,
		enabled = true,
		category = "centrifuging",
		ingredients = { { "stone-debris", 20 } },
		icon = "__base__/graphics/icons/stone.png",
		icon_size = 64,
		icon_mipmaps = 4,
		subgroup = "metallurgy-processes",
		order = "",
		main_product = "",
		results = {
			{
				name = "chromite-ore",
				probability = 0.01,
				amount = 100,
			},
			{
				name = "magnetite-ore",
				probability = 0.01,
				amount = 100,
			},
			{
				name = "malachite-ore",
				probability = 0.01,
				amount = 100,
			},
			{
				name = "monazite-ore",
				probability = 0.01,
				amount = 100,
			},
			{
				name = "laterite-ore",
				probability = 0.01,
				amount = 100,
			},
			{
				name = "ilmenite-ore",
				probability = 0.01,
				amount = 100,
			},
			{
				name = "limonite-ore",
				probability = 0.01,
				amount = 100,
			},
			{
				name = "stone",
				probability = 0.9,
				amount = 200,
			},
		},
		allow_decomposition = false,
	},
	{
		type = "recipe",
		name = "stone-sifting",
		energy_required = 20,
		enabled = true,
		category = "centrifuging",
		ingredients = { { "stone", 20 } },
		icon = "__base__/graphics/icons/stone.png",
		icon_size = 64,
		icon_mipmaps = 4,
		subgroup = "metallurgy-processes",
		order = "",
		main_product = "",
		results = {
			{
				name = "chromite-ore",
				probability = 0.01,
				amount = 10,
			},
			{
				name = "magnetite-ore",
				probability = 0.1,
				amount = 10,
			},
			{
				name = "malachite-ore",
				probability = 0.1,
				amount = 10,
			},
			{
				name = "monazite-ore",
				probability = 0.05,
				amount = 10,
			},
			{
				name = "bauxite-ore",
				probability = 0.05,
				amount = 10,
			},
			{
				name = "cobaltite-ore",
				probability = 0.05,
				amount = 10,
			},
			{
				name = "limonite-ore",
				probability = 0.05,
				amount = 10,
			},
			{
				name = "ilmenite-ore",
				probability = 0.05,
				amount = 10,
			},
			{
				name = "rare-earth-ore",
				probability = 0.05,
				amount = 10,
			},
			{
				name = "stone",
				probability = 0.5,
				amount = 10,
			},
		},
		allow_decomposition = false,
	},

	--Fluids, Chemistry
	{
		type = "recipe",
		name = "motor-oil",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 20,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "lubricant", amount = 20 },
			{ type = "fluid", name = "light-oil", amount = 20 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "motor-oil", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "coolant",
		category = "chemistry",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 20,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "lubricant", amount = 20 },
			{ type = "fluid", name = "nitrogen", amount = 40 },
		},
		results = {
			{ type = "fluid", name = "coolant", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "chemical-oil-processing",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "chemical-oil", amount = 50 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "crude-oil", amount = 50 },
			{ type = "fluid", name = "chemical-water", amount = 25 },
			{ type = "fluid", name = "chemical-gas", amount = 25 },
		},
	},
	{
		type = "recipe",
		name = "mineral-water-cracking",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "crude-oil", amount = 50 },
			{ type = "fluid", name = "steam", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "mineral-oil", amount = 50 },
			{ type = "fluid", name = "chemical-water", amount = 25 },
			{ type = "fluid", name = "petroleum-gas", amount = 25 },
		},
	},
	{
		type = "recipe",
		name = "mineral-oil-processing",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "mineral-oil", amount = 10 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "fluorine", amount = 60 },
			{ type = "fluid", name = "chlorine", amount = 60 },
			{ type = "fluid", name = "heavy-oil", amount = 50 },
		},
	},
	{
		type = "recipe",
		name = "chemical-water-processing",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 3,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "chemical-water", amount = 20 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "liquid-air", amount = 60 },
			{ type = "fluid", name = "chlorine", amount = 60 },
			{ type = "fluid", name = "fluorine", amount = 60 },
		},
	},
	{
		type = "recipe",
		name = "chemical-gas-processing",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "chemical-gas", amount = 20 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "noble-gases", amount = 80 },
			{ type = "fluid", name = "carbon-dioxide", amount = 80 },
			{ type = "fluid", name = "oxygen", amount = 80 },
		},
	},
	{
		type = "recipe",
		name = "liquid-air-processing",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 4,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "liquid-air", amount = 20 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "nitrogen", amount = 40 },
			{ type = "fluid", name = "oxygen", amount = 20 },
			{ type = "fluid", name = "hydrogen", amount = 60 },
		},
	},
	{
		type = "recipe",
		name = "coolant",
		category = "chemistry",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 20,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "lubricant", amount = 20 },
			{ type = "fluid", name = "nitrogen", amount = 40 },
		},
		results = {
			{ type = "fluid", name = "coolant", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "azane-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 60,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "nitrogen", amount = 10 },
			{ type = "fluid", name = "hydrogen", amount = 30 },
			{ type = "fluid", name = "water", amount = 20 },
		},
		results = {
			{ type = "fluid", name = "azane-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "carbonic-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 60,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "hydrogen", amount = 20 },
			{ type = "fluid", name = "carbon-dioxide", amount = 30 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "carbonic-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "nitric-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 60,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "nitrogen", amount = 30 },
			{ type = "fluid", name = "hydrogen", amount = 10 },
			{ type = "fluid", name = "water", amount = 20 },
		},
		results = {
			{ type = "fluid", name = "nitric-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "chloric-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 60,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "hydrogen", amount = 10 },
			{ type = "fluid", name = "chlorine", amount = 10 },
			{ type = "fluid", name = "oxygen", amount = 30 },
		},
		results = {
			{ type = "fluid", name = "chloric-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "muriatic-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 60,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "hydrogen", amount = 10 },
			{ type = "fluid", name = "fluorine", amount = 10 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "muriatic-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "verelic-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 120,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "nitrogen", amount = 10 },
			{ type = "fluid", name = "oxygen", amount = 20 },
			{ type = "fluid", name = "water", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "verelic-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "caudic-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 120,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "carbon-dioxide", amount = 25 },
			{ type = "fluid", name = "hydrogen", amount = 25 },
			{ type = "fluid", name = "water", amount = 35 },
		},
		results = {
			{ type = "fluid", name = "caudic-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "luret-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 120,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "azane-acid", amount = 10 },
			{ type = "fluid", name = "chloric-acid", amount = 30 },
			{ type = "fluid", name = "water", amount = 20 },
		},
		results = {
			{ type = "fluid", name = "luret-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "buren-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 120,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "carbonic-acid", amount = 30 },
			{ type = "fluid", name = "noble-gases", amount = 30 },
			{ type = "fluid", name = "water", amount = 20 },
		},
		results = {
			{ type = "fluid", name = "buren-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "genhal-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 120,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "muriatic-acid", amount = 10 },
			{ type = "fluid", name = "oxygen", amount = 30 },
			{ type = "fluid", name = "water", amount = 20 },
		},
		results = {
			{ type = "fluid", name = "genhal-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "vixal-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 120,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "noble-gases", amount = 10 },
			{ type = "fluid", name = "fluorine", amount = 30 },
			{ type = "fluid", name = "oxygen", amount = 20 },
		},
		results = {
			{ type = "fluid", name = "vixal-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "phaudec-acid",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 120,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "nitrogen", amount = 10 },
			{ type = "fluid", name = "hydrogen", amount = 30 },
			{ type = "fluid", name = "water", amount = 20 },
		},
		results = {
			{ type = "fluid", name = "phaudec-acid", amount = 100 },
		},
	},
	{
		type = "recipe",
		name = "dilute-acid-solution",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 120,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "lubricant", amount = 10 },
			{ type = "fluid", name = "heavy-oil", amount = 30 },
			{ type = "fluid", name = "coolant", amount = 20 },
		},
		results = {
			{ type = "fluid", name = "dilute-acid-solution", amount = 500 },
		},
	},
	{
		type = "recipe",
		name = "acid-cleaning-solution",
		category = "oil-processing",
		subgroup = "sam-fluid-recipes",
		order = "ba",
		icon = "__base__/graphics/icons/fluid/water.png",
		icon_size = 64,
		icon_mipmaps = 4,
		energy_required = 120,
		enabled = true,
		ingredients = {
			{ type = "fluid", name = "chlorine", amount = 25 },
			{ type = "fluid", name = "hydrogen", amount = 25},
			{ type = "fluid", name = "steam", amount = 20 },
		},
		results = {
			{ type = "fluid", name = "acid-cleaning-solution", amount = 500 },
		},
	},
})
