data:extend({
	{
		type = "autoplace-control",
		name = "magnetite-ore",
		localised_name = { "", "[entity=magnetite-ore] ", { "entity-name.magnetite-ore" } },
		richness = true,
		order = "b-a",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "magnetite",
		localised_name = { "", "[entity=magnetite] ", { "entity-name.magnetite" } },
		richness = true,
		hidden = true,
		order = "b-a",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "iron-deposit",
		localised_name = { "", "[entity=iron-deposit] ", { "entity-name.iron-deposit" } },
		richness = true,
		order = "b-a",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "malachite-ore",
		localised_name = { "", "[entity=malachite-ore] ", { "entity-name.malachite-ore" } },
		richness = true,
		order = "b-b",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "laterite-ore",
		localised_name = { "", "[entity=laterite-ore] ", { "entity-name.laterite-ore" } },
		richness = true,
		order = "b-bc",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "monazite-ore",
		localised_name = { "", "[entity=monazite-ore] ", { "entity-name.monazite-ore" } },
		richness = true,
		order = "b-bd",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "haematite-ore",
		localised_name = { "", "[entity=haematite-ore] ", { "entity-name.haematite-ore" } },
		richness = true,
		order = "b-cd",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "galena-ore",
		localised_name = { "", "[entity=galena-ore] ", { "entity-name.galena-ore" } },
		richness = true,
		order = "b-ce",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "carbonatite-ore",
		localised_name = { "", "[entity=carbonatite-ore] ", { "entity-name.carbonatite-ore" } },
		richness = true,
		order = "b-de",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "chromite-ore",
		localised_name = { "", "[entity=chromite-ore] ", { "entity-name.chromite-ore" } },
		richness = true,
		order = "b-fe",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "oil-shale",
		localised_name = { "", "[entity=oil-shale] ", { "entity-name.oil-shale" } },
		richness = true,
		order = "b-bd",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "aquatic-ore",
		localised_name = { "", "[entity=aquatic-ore] ", { "entity-name.aquatic-ore" } },
		richness = true,
		order = "b-bd",
		category = "resource",
	},
		
})
